# Generated by Django 3.1.6 on 2021-03-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sex', models.CharField(max_length=1)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('transaction_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.customer')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('stars', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.customer')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRepairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('repair_date', models.DateTimeField()),
                ('remarks', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.customer')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('front_camera', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('ram', models.PositiveIntegerField()),
                ('battery_capacity', models.PositiveIntegerField()),
                ('battery_type', models.CharField(max_length=50)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.phone')),
            ],
        ),
    ]
