# Generated by Django 3.1.6 on 2021-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedetails',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
