# Generated by Django 3.1.6 on 2021-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_phonedetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedetails',
            name='storage',
            field=models.CharField(default='56GB', max_length=50),
            preserve_default=False,
        ),
    ]
