# Generated by Django 3.2 on 2021-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_phonedetails_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.TextField()),
                ('phone_details', models.TextField()),
            ],
        ),
    ]
