# Generated by Django 3.2 on 2021-04-15 14:28

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webservice', '0006_alter_phonereviews_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonereviews',
            name='created_by',
        ),
        migrations.AddField(
            model_name='phonerequest',
            name='customer',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phonerepairs',
            name='customer',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phonereviews',
            name='customer',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phonetransactions',
            name='customer',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
